pw_cons_file <- unz("household_power_cons.zip","household_power_consumption.txt")
pw <- read.csv(pw_cons_file,header=TRUE,sep=";",stringsAsFactors=FALSE,dec=".",na.strings="?",colClasses=c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"))
pw$Date <- as.Date(strptime(pw$Date,"%d/%m/%Y"))
pw1 <- subset(pw,as.Date(pw$Date) >= as.Date("2007-02-01") & as.Date(pw$Date) <= as.Date("2007-02-02"))
rm(pw)
pw1$Time <-  strptime(paste(pw1$Date, pw1$Time), "%Y-%m-%d %H:%M:%S")

png("plot4.png",width=480,height=480,antialias="cleartype")
par(mfcol=c(2,2), mar = c(4, 5, 2, 1), oma = c(1, 0, 2, 0))
plot(pw1$Time,pw1$Global_active_power,type="l",xlab="",ylab="Global Active Power")
with(pw1, {
plot(Time,Sub_metering_1,type="n",xlab="",ylab="Energy sub metering")
lines(Time,Sub_metering_1,col="black")
lines(Time,Sub_metering_2,col="red")
lines(Time,Sub_metering_3,col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),lty=c(1,1,1),col=c("black","red","blue"),bty="n")
})
plot(pw1$Time,pw1$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(pw1$Time,pw1$Global_reactive_power,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()
